//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace rzkclock_ws.gutis.rfc.sap.com {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZK_WEBSERVICES_RELOJ_BN", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZK_WEBSERVICES_RELOJ_SN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZkDistrEmpleadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkEnviarHuellasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkGuardarHuellaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkGuardarHuellasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkListaRelojesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkMarcasEmpleadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkPingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkSincTiempoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZkWsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZK_WEBSERVICES_RELOJ_SN() {
            this.Url = global::rzkclock_ws.Properties.Settings.Default.SAP_WS_PRD_ZK;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZkDistrEmpleadosCompletedEventHandler ZkDistrEmpleadosCompleted;
        
        /// <remarks/>
        public event ZkEnviarHuellasCompletedEventHandler ZkEnviarHuellasCompleted;
        
        /// <remarks/>
        public event ZkGuardarHuellaCompletedEventHandler ZkGuardarHuellaCompleted;
        
        /// <remarks/>
        public event ZkGuardarHuellasCompletedEventHandler ZkGuardarHuellasCompleted;
        
        /// <remarks/>
        public event ZkListaRelojesCompletedEventHandler ZkListaRelojesCompleted;
        
        /// <remarks/>
        public event ZkMarcasEmpleadosCompletedEventHandler ZkMarcasEmpleadosCompleted;
        
        /// <remarks/>
        public event ZkPingCompletedEventHandler ZkPingCompleted;
        
        /// <remarks/>
        public event ZkSincTiempoCompletedEventHandler ZkSincTiempoCompleted;
        
        /// <remarks/>
        public event ZkWsCompletedEventHandler ZkWsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkDistrEmpl" +
            "eadosRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkDistrEmpleadosResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkDistrEmpleadosResponse ZkDistrEmpleados([System.Xml.Serialization.XmlElementAttribute("ZkDistrEmpleados", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkDistrEmpleados ZkDistrEmpleados1) {
            object[] results = this.Invoke("ZkDistrEmpleados", new object[] {
                        ZkDistrEmpleados1});
            return ((ZkDistrEmpleadosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkDistrEmpleadosAsync(ZkDistrEmpleados ZkDistrEmpleados1) {
            this.ZkDistrEmpleadosAsync(ZkDistrEmpleados1, null);
        }
        
        /// <remarks/>
        public void ZkDistrEmpleadosAsync(ZkDistrEmpleados ZkDistrEmpleados1, object userState) {
            if ((this.ZkDistrEmpleadosOperationCompleted == null)) {
                this.ZkDistrEmpleadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkDistrEmpleadosOperationCompleted);
            }
            this.InvokeAsync("ZkDistrEmpleados", new object[] {
                        ZkDistrEmpleados1}, this.ZkDistrEmpleadosOperationCompleted, userState);
        }
        
        private void OnZkDistrEmpleadosOperationCompleted(object arg) {
            if ((this.ZkDistrEmpleadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkDistrEmpleadosCompleted(this, new ZkDistrEmpleadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkEnviarHue" +
            "llasRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkEnviarHuellasResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkEnviarHuellasResponse ZkEnviarHuellas([System.Xml.Serialization.XmlElementAttribute("ZkEnviarHuellas", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkEnviarHuellas ZkEnviarHuellas1) {
            object[] results = this.Invoke("ZkEnviarHuellas", new object[] {
                        ZkEnviarHuellas1});
            return ((ZkEnviarHuellasResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkEnviarHuellasAsync(ZkEnviarHuellas ZkEnviarHuellas1) {
            this.ZkEnviarHuellasAsync(ZkEnviarHuellas1, null);
        }
        
        /// <remarks/>
        public void ZkEnviarHuellasAsync(ZkEnviarHuellas ZkEnviarHuellas1, object userState) {
            if ((this.ZkEnviarHuellasOperationCompleted == null)) {
                this.ZkEnviarHuellasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkEnviarHuellasOperationCompleted);
            }
            this.InvokeAsync("ZkEnviarHuellas", new object[] {
                        ZkEnviarHuellas1}, this.ZkEnviarHuellasOperationCompleted, userState);
        }
        
        private void OnZkEnviarHuellasOperationCompleted(object arg) {
            if ((this.ZkEnviarHuellasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkEnviarHuellasCompleted(this, new ZkEnviarHuellasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkGuardarHu" +
            "ellaRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkGuardarHuellaResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkGuardarHuellaResponse ZkGuardarHuella([System.Xml.Serialization.XmlElementAttribute("ZkGuardarHuella", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkGuardarHuella ZkGuardarHuella1) {
            object[] results = this.Invoke("ZkGuardarHuella", new object[] {
                        ZkGuardarHuella1});
            return ((ZkGuardarHuellaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkGuardarHuellaAsync(ZkGuardarHuella ZkGuardarHuella1) {
            this.ZkGuardarHuellaAsync(ZkGuardarHuella1, null);
        }
        
        /// <remarks/>
        public void ZkGuardarHuellaAsync(ZkGuardarHuella ZkGuardarHuella1, object userState) {
            if ((this.ZkGuardarHuellaOperationCompleted == null)) {
                this.ZkGuardarHuellaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkGuardarHuellaOperationCompleted);
            }
            this.InvokeAsync("ZkGuardarHuella", new object[] {
                        ZkGuardarHuella1}, this.ZkGuardarHuellaOperationCompleted, userState);
        }
        
        private void OnZkGuardarHuellaOperationCompleted(object arg) {
            if ((this.ZkGuardarHuellaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkGuardarHuellaCompleted(this, new ZkGuardarHuellaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkGuardarHu" +
            "ellasRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkGuardarHuellasResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkGuardarHuellasResponse ZkGuardarHuellas([System.Xml.Serialization.XmlElementAttribute("ZkGuardarHuellas", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkGuardarHuellas ZkGuardarHuellas1) {
            object[] results = this.Invoke("ZkGuardarHuellas", new object[] {
                        ZkGuardarHuellas1});
            return ((ZkGuardarHuellasResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkGuardarHuellasAsync(ZkGuardarHuellas ZkGuardarHuellas1) {
            this.ZkGuardarHuellasAsync(ZkGuardarHuellas1, null);
        }
        
        /// <remarks/>
        public void ZkGuardarHuellasAsync(ZkGuardarHuellas ZkGuardarHuellas1, object userState) {
            if ((this.ZkGuardarHuellasOperationCompleted == null)) {
                this.ZkGuardarHuellasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkGuardarHuellasOperationCompleted);
            }
            this.InvokeAsync("ZkGuardarHuellas", new object[] {
                        ZkGuardarHuellas1}, this.ZkGuardarHuellasOperationCompleted, userState);
        }
        
        private void OnZkGuardarHuellasOperationCompleted(object arg) {
            if ((this.ZkGuardarHuellasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkGuardarHuellasCompleted(this, new ZkGuardarHuellasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkListaRelo" +
            "jesRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkListaRelojesResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkListaRelojesResponse ZkListaRelojes([System.Xml.Serialization.XmlElementAttribute("ZkListaRelojes", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkListaRelojes ZkListaRelojes1) {
            object[] results = this.Invoke("ZkListaRelojes", new object[] {
                        ZkListaRelojes1});
            return ((ZkListaRelojesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkListaRelojesAsync(ZkListaRelojes ZkListaRelojes1) {
            this.ZkListaRelojesAsync(ZkListaRelojes1, null);
        }
        
        /// <remarks/>
        public void ZkListaRelojesAsync(ZkListaRelojes ZkListaRelojes1, object userState) {
            if ((this.ZkListaRelojesOperationCompleted == null)) {
                this.ZkListaRelojesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkListaRelojesOperationCompleted);
            }
            this.InvokeAsync("ZkListaRelojes", new object[] {
                        ZkListaRelojes1}, this.ZkListaRelojesOperationCompleted, userState);
        }
        
        private void OnZkListaRelojesOperationCompleted(object arg) {
            if ((this.ZkListaRelojesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkListaRelojesCompleted(this, new ZkListaRelojesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkMarcasEmp" +
            "leadosRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkMarcasEmpleadosResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkMarcasEmpleadosResponse ZkMarcasEmpleados([System.Xml.Serialization.XmlElementAttribute("ZkMarcasEmpleados", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkMarcasEmpleados ZkMarcasEmpleados1) {
            object[] results = this.Invoke("ZkMarcasEmpleados", new object[] {
                        ZkMarcasEmpleados1});
            return ((ZkMarcasEmpleadosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkMarcasEmpleadosAsync(ZkMarcasEmpleados ZkMarcasEmpleados1) {
            this.ZkMarcasEmpleadosAsync(ZkMarcasEmpleados1, null);
        }
        
        /// <remarks/>
        public void ZkMarcasEmpleadosAsync(ZkMarcasEmpleados ZkMarcasEmpleados1, object userState) {
            if ((this.ZkMarcasEmpleadosOperationCompleted == null)) {
                this.ZkMarcasEmpleadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkMarcasEmpleadosOperationCompleted);
            }
            this.InvokeAsync("ZkMarcasEmpleados", new object[] {
                        ZkMarcasEmpleados1}, this.ZkMarcasEmpleadosOperationCompleted, userState);
        }
        
        private void OnZkMarcasEmpleadosOperationCompleted(object arg) {
            if ((this.ZkMarcasEmpleadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkMarcasEmpleadosCompleted(this, new ZkMarcasEmpleadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkPingReque" +
            "st", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkPingResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkPingResponse ZkPing([System.Xml.Serialization.XmlElementAttribute("ZkPing", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkPing ZkPing1) {
            object[] results = this.Invoke("ZkPing", new object[] {
                        ZkPing1});
            return ((ZkPingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkPingAsync(ZkPing ZkPing1) {
            this.ZkPingAsync(ZkPing1, null);
        }
        
        /// <remarks/>
        public void ZkPingAsync(ZkPing ZkPing1, object userState) {
            if ((this.ZkPingOperationCompleted == null)) {
                this.ZkPingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkPingOperationCompleted);
            }
            this.InvokeAsync("ZkPing", new object[] {
                        ZkPing1}, this.ZkPingOperationCompleted, userState);
        }
        
        private void OnZkPingOperationCompleted(object arg) {
            if ((this.ZkPingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkPingCompleted(this, new ZkPingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkSincTiemp" +
            "oRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkSincTiempoResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkSincTiempoResponse ZkSincTiempo([System.Xml.Serialization.XmlElementAttribute("ZkSincTiempo", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkSincTiempo ZkSincTiempo1) {
            object[] results = this.Invoke("ZkSincTiempo", new object[] {
                        ZkSincTiempo1});
            return ((ZkSincTiempoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkSincTiempoAsync(ZkSincTiempo ZkSincTiempo1) {
            this.ZkSincTiempoAsync(ZkSincTiempo1, null);
        }
        
        /// <remarks/>
        public void ZkSincTiempoAsync(ZkSincTiempo ZkSincTiempo1, object userState) {
            if ((this.ZkSincTiempoOperationCompleted == null)) {
                this.ZkSincTiempoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkSincTiempoOperationCompleted);
            }
            this.InvokeAsync("ZkSincTiempo", new object[] {
                        ZkSincTiempo1}, this.ZkSincTiempoOperationCompleted, userState);
        }
        
        private void OnZkSincTiempoOperationCompleted(object arg) {
            if ((this.ZkSincTiempoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkSincTiempoCompleted(this, new ZkSincTiempoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZK_WEBSERVICES_RELOJ:ZkWsRequest" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZkWsResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZkWsResponse ZkWs([System.Xml.Serialization.XmlElementAttribute("ZkWs", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZkWs ZkWs1) {
            object[] results = this.Invoke("ZkWs", new object[] {
                        ZkWs1});
            return ((ZkWsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZkWsAsync(ZkWs ZkWs1) {
            this.ZkWsAsync(ZkWs1, null);
        }
        
        /// <remarks/>
        public void ZkWsAsync(ZkWs ZkWs1, object userState) {
            if ((this.ZkWsOperationCompleted == null)) {
                this.ZkWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZkWsOperationCompleted);
            }
            this.InvokeAsync("ZkWs", new object[] {
                        ZkWs1}, this.ZkWsOperationCompleted, userState);
        }
        
        private void OnZkWsOperationCompleted(object arg) {
            if ((this.ZkWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZkWsCompleted(this, new ZkWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkDistrEmpleados {
        
        private string empleadoField;
        
        private ZksStatusEmple[] infoField;
        
        private string relojField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksStatusEmple[] Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reloj {
            get {
                return this.relojField;
            }
            set {
                this.relojField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZksStatusEmple {
        
        private string ipField;
        
        private string bdegrField;
        
        private string pernrField;
        
        private string cnameField;
        
        private string enableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bdegr {
            get {
                return this.bdegrField;
            }
            set {
                this.bdegrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cname {
            get {
                return this.cnameField;
            }
            set {
                this.cnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZksMarcas {
        
        private string ipField;
        
        private string pernrField;
        
        private string modoField;
        
        private string tipoField;
        
        private string fechaField;
        
        private string horaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Modo {
            get {
                return this.modoField;
            }
            set {
                this.modoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktReloj {
        
        private string mandtField;
        
        private string bdegrField;
        
        private string ipField;
        
        private string landField;
        
        private string estadoField;
        
        private string infoField;
        
        private string ubicacionField;
        
        private string idField;
        
        private string macaddField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bdegr {
            get {
                return this.bdegrField;
            }
            set {
                this.bdegrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Macadd {
            get {
                return this.macaddField;
            }
            set {
                this.macaddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZksHuellas {
        
        private string pernrField;
        
        private string dedoField;
        
        private short dtint2Field;
        
        private string huellaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dedo {
            get {
                return this.dedoField;
            }
            set {
                this.dedoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short Dtint2 {
            get {
                return this.dtint2Field;
            }
            set {
                this.dtint2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Huella {
            get {
                return this.huellaField;
            }
            set {
                this.huellaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkDistrEmpleadosResponse {
        
        private ZksStatusEmple[] infoField;
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksStatusEmple[] Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkEnviarHuellas {
        
        private string empleadoField;
        
        private ZksHuellas[] huellasField;
        
        private string relojField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksHuellas[] Huellas {
            get {
                return this.huellasField;
            }
            set {
                this.huellasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reloj {
            get {
                return this.relojField;
            }
            set {
                this.relojField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkEnviarHuellasResponse {
        
        private ZksHuellas[] huellasField;
        
        private string ipField;
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksHuellas[] Huellas {
            get {
                return this.huellasField;
            }
            set {
                this.huellasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkGuardarHuella {
        
        private string dedoField;
        
        private string empleadoField;
        
        private string huellaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dedo {
            get {
                return this.dedoField;
            }
            set {
                this.dedoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Huella {
            get {
                return this.huellaField;
            }
            set {
                this.huellaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkGuardarHuellaResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkGuardarHuellas {
        
        private ZksHuellas[] huellasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksHuellas[] Huellas {
            get {
                return this.huellasField;
            }
            set {
                this.huellasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkGuardarHuellasResponse {
        
        private ZksHuellas[] huellasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksHuellas[] Huellas {
            get {
                return this.huellasField;
            }
            set {
                this.huellasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkListaRelojes {
        
        private ZktReloj[] relojesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktReloj[] Relojes {
            get {
                return this.relojesField;
            }
            set {
                this.relojesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkListaRelojesResponse {
        
        private ZktReloj[] relojesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktReloj[] Relojes {
            get {
                return this.relojesField;
            }
            set {
                this.relojesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkMarcasEmpleados {
        
        private ZksMarcas[] marcasField;
        
        private string soloPostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksMarcas[] Marcas {
            get {
                return this.marcasField;
            }
            set {
                this.marcasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SoloPost {
            get {
                return this.soloPostField;
            }
            set {
                this.soloPostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkMarcasEmpleadosResponse {
        
        private string idocNumField;
        
        private ZksMarcas[] marcasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdocNum {
            get {
                return this.idocNumField;
            }
            set {
                this.idocNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZksMarcas[] Marcas {
            get {
                return this.marcasField;
            }
            set {
                this.marcasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkPing {
        
        private string estadoField;
        
        private string ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkPingResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkSincTiempo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkSincTiempoResponse {
        
        private string datumField;
        
        private System.DateTime uzeitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time")]
        public System.DateTime Uzeit {
            get {
                return this.uzeitField;
            }
            set {
                this.uzeitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkWs {
        
        private string codigoField;
        
        private string comandoField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comando {
            get {
                return this.comandoField;
            }
            set {
                this.comandoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkWsResponse {
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkDistrEmpleadosCompletedEventHandler(object sender, ZkDistrEmpleadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkDistrEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkDistrEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkDistrEmpleadosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkDistrEmpleadosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkEnviarHuellasCompletedEventHandler(object sender, ZkEnviarHuellasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkEnviarHuellasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkEnviarHuellasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkEnviarHuellasResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkEnviarHuellasResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkGuardarHuellaCompletedEventHandler(object sender, ZkGuardarHuellaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkGuardarHuellaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkGuardarHuellaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkGuardarHuellaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkGuardarHuellaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkGuardarHuellasCompletedEventHandler(object sender, ZkGuardarHuellasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkGuardarHuellasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkGuardarHuellasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkGuardarHuellasResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkGuardarHuellasResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkListaRelojesCompletedEventHandler(object sender, ZkListaRelojesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkListaRelojesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkListaRelojesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkListaRelojesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkListaRelojesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkMarcasEmpleadosCompletedEventHandler(object sender, ZkMarcasEmpleadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkMarcasEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkMarcasEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkMarcasEmpleadosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkMarcasEmpleadosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkPingCompletedEventHandler(object sender, ZkPingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkPingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkPingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkPingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkPingResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkSincTiempoCompletedEventHandler(object sender, ZkSincTiempoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkSincTiempoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkSincTiempoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkSincTiempoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkSincTiempoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ZkWsCompletedEventHandler(object sender, ZkWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZkWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZkWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZkWsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZkWsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591